<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CG_CreateGist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>572fecff-3a0b-470a-9fbe-9099c74a624d</testSuiteGuid>
   <testCaseLink>
      <guid>ae978922-56e8-44fc-a177-a686ea9920c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CG_CreateGist</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1d63ffee-39b1-4b0c-b38f-bd7ce03d252c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_CG_CreateGist</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>1d63ffee-39b1-4b0c-b38f-bd7ce03d252c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>element_text</value>
         <variableId>3fc924d8-9aae-4115-b7bf-7805d6c3031d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6577c77-533d-4fbb-b00e-7fdf071e722f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4065c29-ba7e-46ef-b50f-60f17f72baee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e696a543-8aa2-41b7-bc7d-fefec4bc9b61</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
