<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_gist_text</name>
   <tag></tag>
   <elementGuidId>5c0aca1d-7ef0-4b3d-a3d5-9009300e272e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.CodeMirror-line</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//pre[@class = 'CodeMirror-line' and @role = 'presentation']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/main/div[2]/div/form/div/div[1]/div[2]/div/div[2]/div/div[5]/div[1]/div/div/div/div[5]/div/pre/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CodeMirror-line</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>pre</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;CodeMirror-code&quot;]/div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
</WebElementEntity>
